#pragma once

// --- AXP2101 PMIC HARDWARE DEFINITIONS ---
#define PMIC_I2C_ADDR          0x34
#define PMIC_REG_DLDO1_CTRL    0x99
#define PMIC_REG_BAT_PERCENT   0xA4

#define PMIC_DLDO1_3V4_MAX     0x1D
#define PMIC_DLDO1_2V7_DIM     0x16
#define PMIC_DLDO1_0V5_OFF     0x00

// --- CHARGING REGISTERS ---
#define PMIC_REG_VBUS_VOLTAGE  0x15
#define PMIC_REG_VBUS_LIMIT    0x16
#define PMIC_REG_CHG_CTRL      0x18
#define PMIC_REG_CHG_CURRENT   0x62

// --- TELEMETRY REGISTERS ---
#define PMIC_REG_PMU_STATUS    0x00
#define PMIC_REG_CHG_STATUS    0x01

#define PMIC_REG_LDO_ONOFF     0x90
